name: Deploy on Ubuntu Server

on:
    push:
        branches:
            - main

jobs:
    push-file-to-server:
        name: Push Static Files into Server
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server
              run: |
                  rsync -avz --no-t -e "ssh -o StrictHostKeyChecking=no" \
                  ./ \
                  ${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_IP }}:${{ vars.DIR_PATH }}
