name: Deploy on Ubuntu Server

on:
    push:
        branches:
            - main

jobs:
    push-file-to-server:
        name: Push Static Files into Server
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Runs commands on remote server
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_IP }}  << 'EOF'
                  echo "Deploying application"
                  echo "cd to ${{ vars.DEPLOYMENT_DIR }}"
                  cd ${{ vars.DEPLOYMENT_DIR }}
                  echo "Deleting ${{ vars.REPO_NAME }}"
                  sudo rm -rf ${{ vars.REPO_NAME }}
                  sudo git clone https://github.com/sauravkhanal/${{ vars.REPO_NAME }}.git
                  echo "Deployment complete"
                  EOF